services:
  story-template:
    platform: linux/amd64
    image: pipeline/dev
    ports:
      - 8180:8180
      - 5178:5178
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - ~/.gitconfig:/home/node/.gitconfig-host:ro
    command: tail -f /dev/stdout
    working_dir: /app
    user: node
    tty: true
